### ISSUE TITLE
Failed downloads not detected. Links stay in list (0.0.5)

### ISSUE THREAD

**Issue by Ultrawipf** [akshat1/video-hoarder#37]
If an added link fails to download with an exception it stays in the pending list forever until the container is restarted and does not get cleared with the clear button or on site reload.

Tested on 0.0.5 (381571e)

Example log:
```
UnhandledPromiseRejectionWarning: Error: Command failed: youtube-dl --get-title http://badurl.nope
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://badurl.nope

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)```

**Comment by akshat1** [comment]
Github closed this issue because it was referenced in a PR. However the fix hasn't made it to the release yet, so re-opening for a bit.

**Comment by akshat1** [comment]
Now in release branch. Docker image (:latest) should be out soon. Closing.
